version: '3.7'
services:
  web:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    image: postgres:14.0-alpine
    container_name: postgres_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
volumes:
  postgres_data: